import the necessary libraries and run them so that  we can use further in building a model:
Pandas:
Pandas is a versatile data manipulation library for Python, providing easy-to-use data structures and data analysis tools.
Numpy:NumPy is a fundamental library for scientific computing in Python, offering powerful multidimensional array operations and mathematical functions
Matplotlib:
Matplotlib is a comprehensive plotting library for Python, enabling the creation of high-quality visualizations for data exploration and presentation
Seaborn:Seaborn is a statistical data visualization library in Python that provides beautiful and informative visualizations for exploring and understanding data.
sklearn:
Scikit-learn (sklearn) is a widely-used machine learning library in Python, offering a comprehensive suite of tools for various tasks such as classification, regression, clustering, model selection, and evaluation.

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_curve, roc_auc_score
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import scipy
import joblib
import os

As we have 2 folders in the dataset of kronodroid,here in this file we are going to work on realdevice,in which it has malware and goodware,

In [53]:
dx=pd.read_csv('/content/real_legitimate_v1.csv')

In [54]:
dy=pd.read_csv('/content/real_malware_v1.csv')

In [55]:
df = pd.concat([dx, dy], ignore_index=True)
df.to_csv('combined.csv', index=False)

In [56]:
df = df.sample(frac=1).reset_index(drop=True)
df=df.to_csv('shuffled_dataset.csv', index=False)

In [57]:
dr=pd.read_csv('/content/shuffled_dataset.csv')

<ipython-input-57-a12dd414d2f0>:1: DtypeWarning: Columns (472,473,474,475,476,477,478,479,480) have mixed types. Specify dtype option on import or set low_memory=False.
  dr=pd.read_csv('/content/shuffled_dataset.csv')


In [58]:
data={
    'Package':dr['Package'][:20000],
    'Malware':dr['Malware'][:20000],
    'prctl':dr['prctl'][:20000],
    'sha256':dr['sha256'][:20000],
    'EarliestModDate':dr['EarliestModDate'][:20000],
    'Malware':dr['Malware'][:20000],
    'write': dr['write'][:20000],
    'read':dr['read'][:20000],
    'write':dr['write'][:20000],
    'munmap':dr['munmap'][:20000],
    'mprotect':dr['mprotect'][:20000],
    'madvise':dr['madvise'][:20000],
    'ioctl':dr['ioctl'][:20000],
    'writev':dr['writev'][:20000],
    'dup':dr['dup'][:20000],
    'lseek':dr['lseek'][:20000],
    'mmap2':dr['mmap2'][:20000],
    'fstat64':dr['fstat64'][:20000],
    'rt_sigprocmask':dr['rt_sigprocmask'][:20000],
   'recvfrom':dr['recvfrom'][:20000],
    'getsockopt':dr['getsockopt'][:20000],
    'lseek':dr['lseek'][:20000],
    'clock_gettime':dr['clock_gettime'][:20000],
    'futex':dr['futex'][:20000],
    'pread':dr['pread'][:20000],
     'FilesInsideAPK':dr['FilesInsideAPK'][:20000],
   'TimesSubmitted':dr['TimesSubmitted'][:20000],
    'getsockopt':dr['getsockopt'][:20000],
    'Activities':dr['Activities'][:20000],
    'clock_gettime':dr['clock_gettime'][:20000],
    'NrIntActivities':dr['NrIntActivities'][:20000],
    'NrIntActivitiesActions':dr['NrIntActivitiesActions'][:20000],
    'TotalIntentFilters':dr['TotalIntentFilters'][:20000],
    'Scanners':dr['Scanners'][:20000],
    'MalFamily':dr['MalFamily'][:20000]
    }
dg=pd.DataFrame(data)
dg

Package  Malware  prctl  \
0                             org.withouthat.acalendar\n        0      8   
1                   com.f2fgames.games.puppyclear.lite\n        0      8   
2                                  com.gamebox_idtkown\n        1     40   
3                                     ZDH.Book.XiYouJi\n        1     18   
4                                       tdsfn.html.app\n        1    223   
...                                                  ...      ...    ...   
19995  com.telemaque.shopping.fashion_item_sun_glasses\n        0     92   
19996                            com.goodquotes.widget\n        0      6   
19997                               com.android.system\n        1     30   
19998                        com.itatech.barcelonanews\n        1     25   
19999                                com.keji.danti407\n        1     27   

                                                  sha256 EarliestModDate  \
0      8f6775287d229443634c64c9e0eedde5b033b182e309dc...       7/25/2011   
1      4c3c7676525c5dab10479a6357c2bc7e1fb12b789bee01...       6/30/2011   
2      7e43634f4e98ced272fb60dcd122fa01d8791b1a70701b...        5/4/2018   
3      97fc69942c8b5f53c221af00fd881bc02e2a1ceac3f467...       8/10/2011   
4      be4136eeadd43f3f4fb342a7f7ef771ca2b6a1ff492b0c...      12/13/2013   
...                                                  ...             ...   
19995  6840bc4f802652f66870428a0c2a2e3fcd7c11a9a9f75a...        7/3/2011   
19996  c0e00b42bf312e39c2dde9a1313aa451b1b2feb006b787...      12/28/2010   
19997  6db37c6e0872212e1d525bb5872f3a3e42d588cd5ea396...      11/16/2014   
19998  564dfab63dc9b27f899d263eca5f41730907aea0ff25c6...       7/16/2012   
19999  0dd696cae9f5fc107bac087165a9fb11cd30349541c807...        5/5/2011   

       write  read  munmap  mprotect  madvise  ...  futex  pread  \
0          8     8      14        17        6  ...     24     22   
1          1     1       6         5        6  ...     15     36   
2         84    28      65        44       30  ...    217    130   
3          2     4      40       168       18  ...      4      5   
4       4987  7410      89      1173      109  ...   2779     78   
...      ...   ...     ...       ...      ...  ...    ...    ...   
19995      6    12      57       595       49  ...    179     60   
19996      1     3       0         4        4  ...     10      0   
19997      9    10       1        22       20  ...     37      2   
19998      4     6      49       173       24  ...      7     29   
19999      4     5      52       170       26  ...      7     11   

       FilesInsideAPK  TimesSubmitted  Activities  NrIntActivities  \
0                  45               4           3                2   
1                 131               4           6                1   
2                1067               2         156                5   
3                 119               5           7                1   
4                  40              14           1                1   
...               ...             ...         ...              ...   
19995              21               5           2                1   
19996              19               6           2                1   
19997               9               9           2                1   
19998              34               3           9                1   
19999              95             101           7                1   

       NrIntActivitiesActions  TotalIntentFilters  Scanners  \
0                           2                   3        64   
1                           1                   2        66   
2                           6                   8        63   
3                           1                   1        61   
4                           1                   4        65   
...                       ...                 ...       ...   
19995                       1                   1        66   
19996                       1                   2        66  

In [59]:
sorted_df = dg.sort_values('EarliestModDate')
print(sorted_df)

                               Package  Malware  prctl  \
14913     theredspy15.ltecleanerfoss\n        0      6   
2015        com.dailystats.nhl.kings\n        0    226   
18826                com.adam.aslfms\n        0     12   
18823            com.lon.klrrgzztzlx\n        1    180   
9481              com.oF2pks.jquarks\n        0     87   
...                                ...      ...    ...   
19809        com.hardcoreapps.gatito\n        1     37   
18642  com.hardcoreapps.camionshaker\n        1    263   
2330               bus.Brush.Brother\n        1     51   
7028            phr.fizo.yebwlj.qbbf\n        1     44   
12464        org.opengappsdownloader\n        0      6   

                                                  sha256 EarliestModDate  \
14913  69bd5514fb607799084de987a37f2c1fc10ec4bda8aaaa...        1/1/1980   
2015   aaa64b7f5b1ab44e5b21d2443549dd6db101c95b7a2bb5...        1/1/1980   
18826  a7bad6f39d77f479b4c747e27e917190c279ec2012d9f9...        1/1/1980   

In [60]:
dg=sorted_df
dg

Package  Malware  prctl  \
14913     theredspy15.ltecleanerfoss\n        0      6   
2015        com.dailystats.nhl.kings\n        0    226   
18826                com.adam.aslfms\n        0     12   
18823            com.lon.klrrgzztzlx\n        1    180   
9481              com.oF2pks.jquarks\n        0     87   
...                                ...      ...    ...   
19809        com.hardcoreapps.gatito\n        1     37   
18642  com.hardcoreapps.camionshaker\n        1    263   
2330               bus.Brush.Brother\n        1     51   
7028            phr.fizo.yebwlj.qbbf\n        1     44   
12464        org.opengappsdownloader\n        0      6   

                                                  sha256 EarliestModDate  \
14913  69bd5514fb607799084de987a37f2c1fc10ec4bda8aaaa...        1/1/1980   
2015   aaa64b7f5b1ab44e5b21d2443549dd6db101c95b7a2bb5...        1/1/1980   
18826  a7bad6f39d77f479b4c747e27e917190c279ec2012d9f9...        1/1/1980   
18823  cfd8692593395ed090ac62e1ff8ead3ee7b298686d4793...        1/1/1980   
9481   8da69e215229608a841869c91b9fe565625c165149d0de...        1/1/1980   
...                                                  ...             ...   
19809  3a01126e38722e31e6a934166643e40b88dd19114eae1c...        9/9/2014   
18642  a012a0e8cea37b8b9984dcbe54878ed445024274144a22...        9/9/2014   
2330   416086fc7ef8beafeaebfad7e728d06fac4fd39e440ac1...        9/9/2015   
7028   5bf13a2d16b7a3760e10ad13ede62d9c65a7cec744044b...        9/9/2016   
12464  231c74b67cb10e4c3421a88224bed8116880aa3db69ce3...        9/9/2018   

       write  read  munmap  mprotect  madvise  ...  futex  pread  \
14913     21     7       0         4        4  ...     32      0   
2015     226   228     142       946       87  ...    649    372   
18826     49     9      30         6       10  ...    119    101   
18823     29    18      76       796      102  ...    225     70   
9481       5    12      63       592       45  ...    107     80   
...      ...   ...     ...       ...      ...  ...    ...    ...   
19809      3     9       9        20       18  ...     29     12   
18642    305   209     143       841      111  ...    618    199   
2330      22     7      35       418       33  ...     82     38   
7028      27     7      27       412       29  ...     74     16   
12464     48    33       2         4        4  ...     42      4   

       FilesInsideAPK  TimesSubmitted  Activities  NrIntActivities  \
14913             749              19           5                1   
2015               91               8           7                1   
18826             778              16          10                1   
18823              35               2           9                4   
9481              694              18           5                2   
...               ...             ...         ...              ...   
19809             656               7           5                1   
18642             656               6           5                1   
2330              205               2          21                8   
7028              277               2          24                2   
12464             478              19           3                1   

       NrIntActivitiesActions  TotalIntentFilters  Scanners        MalFamily  
14913                       1                   1        65              NaN  
2015                        1                   1        57              NaN  
18826                       1                  23        65              NaN  
18823                       4                   6        65            Agent  
9481                        6                   5        65              NaN  
...                       ...                 ...       ...              ...  
19809                       1                   2        63  Airpush/StopSMS  
18642                       1                   2        65  Airpush/StopSMS  
2330                        7                  35   

In [61]:
dg.isnull().sum()

Package                      0
Malware                      0
prctl                        0
sha256                       0
EarliestModDate              0
write                        0
read                         0
munmap                       0
mprotect                     0
madvise                      0
ioctl                        0
writev                       0
dup                          0
lseek                        0
mmap2                        0
fstat64                      0
rt_sigprocmask               0
recvfrom                     0
getsockopt                   0
clock_gettime                0
futex                        0
pread                        0
FilesInsideAPK               0
TimesSubmitted               0
Activities                   0
NrIntActivities              0
NrIntActivitiesActions       0
TotalIntentFilters           0
Scanners                     0
MalFamily                 8707
dtype: int64

In [62]:
dg=dg.fillna(0)

In [63]:
dg.isnull().sum()

Package                   0
Malware                   0
prctl                     0
sha256                    0
EarliestModDate           0
write                     0
read                      0
munmap                    0
mprotect                  0
madvise                   0
ioctl                     0
writev                    0
dup                       0
lseek                     0
mmap2                     0
fstat64                   0
rt_sigprocmask            0
recvfrom                  0
getsockopt                0
clock_gettime             0
futex                     0
pread                     0
FilesInsideAPK            0
TimesSubmitted            0
Activities                0
NrIntActivities           0
NrIntActivitiesActions    0
TotalIntentFilters        0
Scanners                  0
MalFamily                 0
dtype: int64

In [64]:
dg.dtypes

Package                   object
Malware                    int64
prctl                      int64
sha256                    object
EarliestModDate           object
write                      int64
read                       int64
munmap                     int64
mprotect                   int64
madvise                    int64
ioctl                      int64
writev                     int64
dup                        int64
lseek                      int64
mmap2                      int64
fstat64                    int64
rt_sigprocmask             int64
recvfrom                   int64
getsockopt                 int64
clock_gettime              int64
futex                      int64
pread                      int64
FilesInsideAPK             int64
TimesSubmitted             int64
Activities                object
NrIntActivities           object
NrIntActivitiesActions    object
TotalIntentFilters        object
Scanners                   int64
MalFamily                 object
dtype: obj

In [65]:
dg.dtypes

Package                   object
Malware                    int64
prctl                      int64
sha256                    object
EarliestModDate           object
write                      int64
read                       int64
munmap                     int64
mprotect                   int64
madvise                    int64
ioctl                      int64
writev                     int64
dup                        int64
lseek                      int64
mmap2                      int64
fstat64                    int64
rt_sigprocmask             int64
recvfrom                   int64
getsockopt                 int64
clock_gettime              int64
futex                      int64
pread                      int64
FilesInsideAPK             int64
TimesSubmitted             int64
Activities                object
NrIntActivities           object
NrIntActivitiesActions    object
TotalIntentFilters        object
Scanners                   int64
MalFamily                 object
dtype: obj

In [66]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
encoded_values = label_encoder.fit_transform(dg['MalFamily'].astype(str))
encoded_values = encoded_values.reshape(-1, 1)
dg['MalFamily'] = encoded_values
dg['MalFamily'].max()
encoded=label_encoder.fit_transform(dg['Package'].astype(str))
dg['Package']=encoded

In [67]:
dg.isnull().sum()

Package                   0
Malware                   0
prctl                     0
sha256                    0
EarliestModDate           0
write                     0
read                      0
munmap                    0
mprotect                  0
madvise                   0
ioctl                     0
writev                    0
dup                       0
lseek                     0
mmap2                     0
fstat64                   0
rt_sigprocmask            0
recvfrom                  0
getsockopt                0
clock_gettime             0
futex                     0
pread                     0
FilesInsideAPK            0
TimesSubmitted            0
Activities                0
NrIntActivities           0
NrIntActivitiesActions    0
TotalIntentFilters        0
Scanners                  0
MalFamily                 0
dtype: int64

In [68]:
dg=dg.fillna(0)

In [69]:
import pandas as pd

In [88]:
if pd.isnull(dg['EarliestModDate']).any():
    # Handle or fill the missing values if necessary
    dg['EarliestModDate'].fillna('fill_value', inplace=True)  # Replace 'fill_value' with an appropriate value
# Convert the 'EarliestModDate' column to datetime
dg['EarliestModDate'] = pd.to_datetime(dg['EarliestModDate'], errors='coerce')

In [71]:

print(dg['EarliestModDate'].dtype)

datetime64[ns]


In [72]:
dg.isnull().sum()

Package                     0
Malware                     0
prctl                       0
sha256                      0
EarliestModDate           379
write                       0
read                        0
munmap                      0
mprotect                    0
madvise                     0
ioctl                       0
writev                      0
dup                         0
lseek                       0
mmap2                       0
fstat64                     0
rt_sigprocmask              0
recvfrom                    0
getsockopt                  0
clock_gettime               0
futex                       0
pread                       0
FilesInsideAPK              0
TimesSubmitted              0
Activities                  0
NrIntActivities             0
NrIntActivitiesActions      0
TotalIntentFilters          0
Scanners                    0
MalFamily                   0
dtype: int64

In [73]:
dg=dg.fillna(0)

In [74]:
dg.isnull().sum()

Package                   0
Malware                   0
prctl                     0
sha256                    0
EarliestModDate           0
write                     0
read                      0
munmap                    0
mprotect                  0
madvise                   0
ioctl                     0
writev                    0
dup                       0
lseek                     0
mmap2                     0
fstat64                   0
rt_sigprocmask            0
recvfrom                  0
getsockopt                0
clock_gettime             0
futex                     0
pread                     0
FilesInsideAPK            0
TimesSubmitted            0
Activities                0
NrIntActivities           0
NrIntActivitiesActions    0
TotalIntentFilters        0
Scanners                  0
MalFamily                 0
dtype: int64

In [151]:
import pandas as pd
import numpy as np

initial_year = "2017-12-31"
dataTrain = dg[dg['EarliestModDate'] <= initial_year]
dataTest = dg[(dg['EarliestModDate'] > initial_year) & (dg['EarliestModDate'] <= '2019-11-30')]
validateData = dg[dg['EarliestModDate'] > '2019-11-30']
print("Train shape:", dataTrain.shape)
print("Test shape:", dataTest.shape)
print("Validate shape:", validateData.shape)


Train shape: (19040, 30)
Test shape: (509, 30)
Validate shape: (72, 30)


In [153]:
from gensim.models import Word2Vec

def feature_extraction(X_dataTrain, X_dataTest):
    # initialize X_train and X_test
    X_train = []
    X_test = []
    # save models used
    models = []
    # iterate over each column of X_dataTrain
    for i in range(X_dataTrain.shape[1]):
        # check column data type
        if np.issubdtype(X_dataTrain.dtype, np.object):
            # train Word2Vec model using column i
            # print("Training column {}...".format(i))
            # get train and test data
            train_data = np.asarray(X_dataTrain[:, i], dtype=str)  # Convert to numpy array
            test_data = np.asarray(X_dataTest[:, i], dtype=str)  # Convert to numpy array
            # initialize and train Word2Vec model
            w2v = Word2Vec(sentences=train_data, vector_size=100, window=5, min_count=1)
            # transform train and test texts to word embeddings
            train_w2v = [w2v.wv[word] if word in w2v.wv else np.zeros(100) for word in train_data]
            test_w2v = [w2v.wv[word] if word in w2v.wv else np.zeros(100) for word in test_data]
            # if first execution, save only features
            if len(X_train) == 0:
                X_train = np.array(train_w2v)
                X_test = np.array(test_w2v)
            # concatenate existing features
            else:
                X_train = np.concatenate((X_train, np.array(train_w2v)), axis=1)
                X_test = np.concatenate((X_test, np.array(test_w2v)), axis=1)
            # save model
            models.append(w2v)
        else:
            # directly concatenate the column as feature
            if len(X_train) == 0:
                X_train = np.array(X_dataTrain[:, i])
                X_test = np.array(X_dataTest[:, i])
            else:
                X_train = np.concatenate((X_train, np.array(X_dataTrain[:, i])), axis=1)
                X_test = np.concatenate((X_test, np.array(X_dataTest[:, i])), axis=1)
    return X_train, X_test


In [154]:
# Normalization method:
def normalization(X_train, X_test):
    from sklearn.preprocessing import MinMaxScaler
    scaler = MinMaxScaler()
    scaler.fit(np.asarray(X_train))
    XX_train = scaler.transform(np.asarray(X_train))
    XX_test = scaler.transform(np.asarray(X_test))
    return XX_train, XX_test
# Iterate over months in test data:


In [ ]:
def normalization(X_train, X_test):
    from sklearn.preprocessing import MinMaxScaler
    from sklearn.impute import SimpleImputer

    # Impute missing values with 0
    imputer = SimpleImputer(strategy='constant', fill_value=0)
    X_train = imputer.fit_transform(X_train)
    X_test = imputer.transform(X_test)

    # Normalize the data
    scaler = MinMaxScaler()
    scaler.fit(X_train)
    X_train_normalized = scaler.transform(X_train)
    X_test_normalized = scaler.transform(X_test)

    return X_train_normalized, X_test_normalized


In [148]:
dataTrain.columns

Index(['Package', 'Malware', 'prctl', 'sha256', 'EarliestModDate', 'write',
       'read', 'munmap', 'mprotect', 'madvise', 'ioctl', 'writev', 'dup',
       'lseek', 'mmap2', 'fstat64', 'rt_sigprocmask', 'recvfrom', 'getsockopt',
       'clock_gettime', 'futex', 'pread', 'FilesInsideAPK', 'TimesSubmitted',
       'Activities', 'NrIntActivities', 'NrIntActivitiesActions',
       'TotalIntentFilters', 'Scanners', 'MalFamily'],
      dtype='object')

In [155]:
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
#from sklearn.ensemble import RandomForestClassifier as Classifier
#from skmultiflow.meta.adaptive_random_forests import AdaptiveRandomForest as Classifier
# group by year-month
from sklearn.linear_model import SGDClassifier as Classifier
dataTestTime = dataTest.groupby([dataTest.EarliestModDate.dt.year, dataTest.EarliestModDate.dt.month])
# get data train labels
y_train = np.array(dataTrain["Malware"])
# remove unused columns from dataTrain
UNUSED_COLUMNS = ["Malware", "sha256", "EarliestModDate"]
for c in UNUSED_COLUMNS:
    del dataTrain[c]
# get dataTrain values
X_dataTrain = dataTrain.values
# arrays to save information
accs = [] # accuracy
f1s = [] # f1score
recall = [] # recall
precision = [] # precision
years = []
months = []
# iterate over year and month
for (year, month), dataTestMonth in dataTestTime:
    # get data test labels
    y_test = np.array(dataTestMonth["Malware"])
    # remove unused columns from data test
    dataTestMonth = dataTestMonth.drop(columns=UNUSED_COLUMNS)
    # get dataTestMonth values
    X_dataTest = dataTestMonth.values
    # feature extraction
    X_train, X_test = feature_extraction(X_dataTrain, X_dataTest)
    # normalization
    print("xtrain",X_train.shape)
    print("xtest",X_test.shape)
    XX_train, XX_test = normalization(X_train, X_test)
    print("xxtrain",XX_train)
    print("xxtest",XX_test.shape)
    # classifier
    # clf = RandomForestClassifier(random_state=0)
    clf = Classifier(random_state=0)
    # train classifier
    clf.fit(XX_train,y_train)
    # predict test data
    y_pred = clf.predict(XX_test)
    print(y_pred)
    # update train data and labels with actual month
    X_dataTrain = np.append(X_dataTrain, X_dataTest, axis=0)
    y_train = np.concatenate((y_train, np.array(y_test)), axis=0)
    print("{}-{}".format(year,month))
    # save metrics
    f1 = f1_score(y_test, y_pred)
    acc = accuracy_score(y_test, y_pred)
    re = recall_score(y_test, y_pred)
    pr = precision_score(y_test, y_pred)
    if (f1 !=0) and (re != 0) and (pr != 0):
        accs.append(acc)
        f1s.append(f1)
        recall.append(re)
        precision.append(pr)
        years.append(year)
        months.append(month)
        print(acc)
from sklearn.metrics import accuracy_score
import math
preds = []
true = []
confidences = []
# iterate over stream
print(XX_test.shape)
for i in range(XX_test.shape[0]):
    # get batch samples
    sample_x = XX_test[i]
    sample_y = y_test[i]
    # predict data
    y_pred = clf.predict([sample_x])
    # save prediction and sample_y
    preds.append(y_pred)
    true.append(sample_y)
    decision_score = clf.decision_function([sample_x])[0]
    confidence_levels = math.exp(decision_score) / (1 + math.exp(decision_score))
    if confidence_levels < 0.9:
        if y_pred == 0:
            print("goodware")
            confidences.append(confidence_levels)
            print("the confidence level is")
            print(confidence_levels)
            print(i)
        else:
            print("malware")
            print(y_pred)
            confidences.append(confidence_levels)
            print("the confidence level is")
            print(confidence_levels)
            print(i)

<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


xtrain (19040, 2700)
xtest (47, 2700)
xxtrain [[1.         0.         0.         ... 0.54002211 0.75311994 0.539985  ]
 [1.         0.         0.         ... 0.54002211 0.75311994 0.539985  ]
 [1.         0.         0.         ... 0.54002211 0.75311994 0.539985  ]
 ...
 [1.         0.         0.         ... 0.6224691  0.89365071 0.1374487 ]
 [1.         0.         0.         ... 1.         1.         0.        ]
 [1.         0.         0.         ... 0.24446536 0.61075633 0.31401341]]
xxtest (47, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 1 1]
2018-1
0.9787234042553191


xtrain (19087, 2700)
xtest (161, 2700)
xxtrain [[1.         0.         0.         ... 0.49973633 0.76781534 0.58056007]
 [1.         0.         0.         ... 0.49973633 0.76781534 0.58056007]
 [1.         0.         0.         ... 0.49973633 0.76781534 0.58056007]
 ...
 [1.         0.         0.         ... 1.         1.         0.        ]
 [1.         0.         0.         ... 1.         1.         0.        ]
 [1.         0.         0.         ... 1.         1.         0.        ]]
xxtest (161, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
2018-2
0.9937888198757764


xtrain (19248, 2700)
xtest (84, 2700)
xxtrain [[1.         0.         0.         ... 0.45367679 0.73416656 0.62766876]
 [1.         0.         0.         ... 0.45367679 0.73416656 0.62766876]
 [1.         0.         0.         ... 0.45367679 0.73416656 0.62766876]
 ...
 [1.         0.         0.         ... 1.         0.92443637 0.        ]
 [1.         0.         0.         ... 1.         0.92443637 0.        ]
 [1.         0.         0.         ... 1.         0.92443637 0.        ]]
xxtest (84, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1]
2018-3
1.0


xtrain (19332, 2700)
xtest (11, 2700)
xxtrain [[1.         0.         0.         ... 0.52186235 0.77854017 0.69445435]
 [1.         0.         0.         ... 0.52186235 0.77854017 0.69445435]
 [1.         0.         0.         ... 0.52186235 0.77854017 0.69445435]
 ...
 [1.         0.         0.         ... 1.         1.         0.1072281 ]
 [1.         0.         0.         ... 1.         1.         0.1072281 ]
 [1.         0.         0.         ... 1.         1.         0.1072281 ]]
xxtest (11, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[1 1 0 1 1 1 1 1 1 1 1]
2018-4
1.0


xtrain (19343, 2700)
xtest (81, 2700)
xxtrain [[1.         0.         0.         ... 0.39680774 0.76303913 0.64882829]
 [1.         0.         0.         ... 0.39680774 0.76303913 0.64882829]
 [1.         0.         0.         ... 0.39680774 0.76303913 0.64882829]
 ...
 [1.         0.         0.         ... 1.         0.99997069 0.03348531]
 [1.         0.         0.         ... 1.         0.99997069 0.03348531]
 [1.         0.         0.         ... 1.         0.99997069 0.03348531]]
xxtest (81, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 1 1 1]
2018-5
1.0


xtrain (19424, 2700)
xtest (53, 2700)
xxtrain [[1.         0.         0.         ... 0.41845156 0.66675217 0.65914183]
 [1.         0.         0.         ... 0.41845156 0.66675217 0.65914183]
 [1.         0.         0.         ... 0.41845156 0.66675217 0.65914183]
 ...
 [1.         0.         0.         ... 1.         0.3859375  0.20042147]
 [1.         0.         0.         ... 0.26697932 0.71166522 0.18855299]
 [1.         0.         0.         ... 0.26697932 0.71166522 0.18855299]]
xxtest (53, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1]
2018-6
1.0


xtrain (19477, 2700)
xtest (6, 2700)
xxtrain [[1.         0.         0.         ... 0.49633067 0.68558856 0.59634387]
 [1.         0.         0.         ... 0.49633067 0.68558856 0.59634387]
 [1.         0.         0.         ... 0.49633067 0.68558856 0.59634387]
 ...
 [1.         0.         0.         ... 0.2365935  0.5115043  0.40612259]
 [1.         0.         0.         ... 0.2365935  0.5115043  0.40612259]
 [1.         0.         0.         ... 0.2365935  0.5115043  0.40612259]]
xxtest (6, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[1 1 1 1 1 1]
2018-7
1.0


xtrain (19483, 2700)
xtest (4, 2700)
xxtrain [[1.         0.         0.         ... 0.41867749 0.6683708  0.6942082 ]
 [1.         0.         0.         ... 0.41867749 0.6683708  0.6942082 ]
 [1.         0.         0.         ... 0.41867749 0.6683708  0.6942082 ]
 ...
 [1.         0.         0.         ... 0.35151081 0.6429184  0.28099292]
 [1.         0.         0.         ... 1.         1.         0.        ]
 [1.         0.         0.         ... 1.         1.         0.        ]]
xxtest (4, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[1 1 1 1]
2018-8
1.0


xtrain (19487, 2700)
xtest (2, 2700)
xxtrain [[1.         0.         0.         ... 0.31289526 0.60954176 0.76374247]
 [1.         0.         0.         ... 0.31289526 0.60954176 0.76374247]
 [1.         0.         0.         ... 0.31289526 0.60954176 0.76374247]
 ...
 [1.         0.         0.         ... 0.2262035  0.57977634 0.38988846]
 [1.         0.         0.         ... 0.2262035  0.57977634 0.38988846]
 [1.         0.         0.         ... 0.2262035  0.57977634 0.38988846]]
xxtest (2, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[1 1]
2018-9
0.5


xtrain (19489, 2700)
xtest (2, 2700)
xxtrain [[1.         0.         0.         ... 0.44426341 0.69503286 0.66018188]
 [1.         0.         0.         ... 0.44426341 0.69503286 0.66018188]
 [1.         0.         0.         ... 0.44426341 0.69503286 0.66018188]
 ...
 [1.         0.         0.         ... 0.27294393 0.62521953 0.36521488]
 [1.         0.         0.         ... 0.27294393 0.62521953 0.36521488]
 [1.         0.         0.         ... 1.         1.         0.        ]]
xxtest (2, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[1 1]
2018-10
1.0


xtrain (19491, 2700)
xtest (3, 2700)
xxtrain [[1.         0.         0.         ... 0.39366385 0.65204383 0.66344108]
 [1.         0.         0.         ... 0.39366385 0.65204383 0.66344108]
 [1.         0.         0.         ... 0.39366385 0.65204383 0.66344108]
 ...
 [1.         0.         0.         ... 1.         1.         0.        ]
 [1.         0.         0.         ... 0.24289276 0.59636578 0.3709372 ]
 [1.         0.         0.         ... 0.24289276 0.59636578 0.3709372 ]]
xxtest (3, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[0 1 1]
2018-11
1.0


xtrain (19494, 2700)
xtest (3, 2700)
xxtrain [[1.         0.         0.         ... 0.38120755 0.67357411 0.67029264]
 [1.         0.         0.         ... 0.38120755 0.67357411 0.67029264]
 [1.         0.         0.         ... 0.38120755 0.67357411 0.67029264]
 ...
 [1.         0.         0.         ... 0.38120755 0.67357411 0.67029264]
 [1.         0.         0.         ... 0.21456438 0.5937956  0.37015038]
 [1.         0.         0.         ... 0.21456438 0.5937956  0.37015038]]
xxtest (3, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[1 1 0]
2018-12
1.0


xtrain (19497, 2700)
xtest (3, 2700)
xxtrain [[1.         0.         0.         ... 0.48208281 0.70606467 0.58344748]
 [1.         0.         0.         ... 0.48208281 0.70606467 0.58344748]
 [1.         0.         0.         ... 0.48208281 0.70606467 0.58344748]
 ...
 [1.         0.         0.         ... 1.         1.         0.        ]
 [1.         0.         0.         ... 0.28761776 0.5966291  0.35413712]
 [1.         0.         0.         ... 0.48208281 0.70606467 0.58344748]]
xxtest (3, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[1 0 1]
2019-2
1.0


xtrain (19500, 2700)
xtest (1, 2700)
xxtrain [[1.         0.         0.         ... 0.43303046 0.6684837  0.64054979]
 [1.         0.         0.         ... 0.43303046 0.6684837  0.64054979]
 [1.         0.         0.         ... 0.43303046 0.6684837  0.64054979]
 ...
 [1.         0.         0.         ... 1.         1.         0.        ]
 [1.         0.         0.         ... 0.43303046 0.6684837  0.64054979]
 [1.         0.         0.         ... 1.         1.         0.        ]]
xxtest (1, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[1]
2019-3
1.0


xtrain (19501, 2700)
xtest (3, 2700)
xxtrain [[1.         0.         0.         ... 0.43619235 0.7022282  0.64291554]
 [1.         0.         0.         ... 0.43619235 0.7022282  0.64291554]
 [1.         0.         0.         ... 0.43619235 0.7022282  0.64291554]
 ...
 [1.         0.         0.         ... 0.43619235 0.7022282  0.64291554]
 [1.         0.         0.         ... 1.         1.         0.        ]
 [1.         0.         0.         ... 1.         1.         0.        ]]
xxtest (3, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[1 1 1]
2019-4
1.0


xtrain (19504, 2700)
xtest (6, 2700)
xxtrain [[1.         0.         0.         ... 0.43972156 0.68713418 0.64069526]
 [1.         0.         0.         ... 0.43972156 0.68713418 0.64069526]
 [1.         0.         0.         ... 0.43972156 0.68713418 0.64069526]
 ...
 [1.         0.         0.         ... 0.22723797 0.5707616  0.47624758]
 [1.         0.         0.         ... 1.         1.         0.        ]
 [1.         0.         0.         ... 1.         1.         0.        ]]
xxtest (6, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[1 1 1 0 1 1]
2019-5
1.0


xtrain (19510, 2700)
xtest (3, 2700)
xxtrain [[1.         0.         0.         ... 0.50380846 0.76451283 0.55412443]
 [1.         0.         0.         ... 0.50380846 0.76451283 0.55412443]
 [1.         0.         0.         ... 0.50380846 0.76451283 0.55412443]
 ...
 [1.         0.         0.         ... 0.50380846 0.76451283 0.55412443]
 [1.         0.         0.         ... 0.25293643 0.56964879 0.37654495]
 [1.         0.         0.         ... 1.         1.         0.        ]]
xxtest (3, 2700)


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1609: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `obj

[0 0 0]
2019-8


xtrain (19513, 2700)
xtest (2, 2700)
xxtrain [[1.         0.         0.         ... 0.41719196 0.7384897  0.69240372]
 [1.         0.         0.         ... 0.41719196 0.7384897  0.69240372]
 [1.         0.         0.         ... 0.41719196 0.7384897  0.69240372]
 ...
 [1.         0.         0.         ... 0.41719196 0.7384897  0.69240372]
 [1.         0.         0.         ... 0.41719196 0.7384897  0.69240372]
 [1.         0.         0.         ... 0.41719196 0.7384897  0.69240372]]
xxtest (2, 2700)


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[0 0]
2019-9


xtrain (19515, 2700)
xtest (8, 2700)
xxtrain [[1.         0.         0.         ... 0.37172573 0.71797951 0.66251847]
 [1.         0.         0.         ... 0.37172573 0.71797951 0.66251847]
 [1.         0.         0.         ... 0.37172573 0.71797951 0.66251847]
 ...
 [1.         0.         0.         ... 0.37172573 0.71797951 0.66251847]
 [1.         0.         0.         ... 1.         1.         0.        ]
 [1.         0.         0.         ... 0.37172573 0.71797951 0.66251847]]
xxtest (8, 2700)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


[0 1 1 1 1 1 1 1]
2019-10
1.0


xtrain (19523, 2700)
xtest (26, 2700)
xxtrain [[1.         0.         0.         ... 0.3663453  0.72021425 0.69520375]
 [1.         0.         0.         ... 0.3663453  0.72021425 0.69520375]
 [1.         0.         0.         ... 0.3663453  0.72021425 0.69520375]
 ...
 [1.         0.         0.         ... 1.         1.         0.        ]
 [1.         0.         0.         ... 1.         1.         0.        ]
 [1.         0.         0.         ... 1.         1.         0.        ]]
xxtest (26, 2700)
[1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1]
2019-11
1.0
(26, 2700)
goodware
the confidence level is
0.00776947238463927
3
goodware
the confidence level is
4.8356308597365495e-06
23


In [150]:
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.linear_model import SGDClassifier as Classifier
dataTestTime = dataTest.groupby([dataTest.EarliestModDate.dt.year, dataTest.EarliestModDate.dt.month])
y_train = np.array(dataTrain["Malware"])
UNUSED_COLUMNS = ["Malware", "sha256", "EarliestModDate"]
for c in UNUSED_COLUMNS:
    del dataTrain[c]
X_dataTrain = dataTrain.values
accs = [] # accuracy
f1s = [] # f1score
recall = [] # recall
precision = [] # precision
years = []
months = []
for (year, month), dataTestMonth in dataTestTime:
    y_test = np.array(dataTestMonth["Malware"])

    for c in UNUSED_COLUMNS:
        del dataTestMonth[c]

    X_dataTest = dataTestMonth.values
    X_train, X_test = feature_extraction(X_dataTrain, X_dataTest)
    print("X_train",X_train)
    print("X_test",X_test.shape)
    print("X_trshape",X_train.shape)
    XX_train, XX_test = normalization(X_train, X_test)
    print("XX_test",XX_test.shape)
    clf = Classifier(random_state=0)
    clf.fit(XX_train, y_train)
    y_pred = clf.predict(XX_test)

    X_dataTrain = np.append(X_dataTrain, X_dataTest, axis=0)
    y_train = np.concatenate((y_train, np.array(y_test)), axis=0)
    print("{}-{}".format(year,month))
    f1 = f1_score(y_test, y_pred)
    acc = accuracy_score(y_test, y_pred)
    re = recall_score(y_test, y_pred)
    pr = precision_score(y_test, y_pred)
    if (f1 != 0) and (re != 0) and (pr != 0):
        accs.append(acc)
        f1s.append(f1)
        recall.append(re)
        precision.append(pr)
        years.append(year)
        months.append(month)
        print(acc)

from sklearn.metrics import accuracy_score
import math

preds = []
true = []
confidences = []

for i in range(XX_test.shape[0]):
    sample_x = XX_test[i]
    sample_y = y_test[i]
    y_pred = clf.predict([sample_x])
    preds.append(y_pred)
    true.append(sample_y)
    decision_score = clf.decision_function([sample_x])[0]
    confidence_levels = math.exp(decision_score) / (1 + math.exp(decision_score))
    if confidence_levels < 0.9:
        if y_pred == 0:
            print("goodware")
            confidences.append(confidence_levels)
            print("the confidence level is")
            print(confidence_levels)
            print(i)
        else:
            print("malware")
            print(y_pred)
            confidences.append(confidence_levels)
            print("the confidence level is")
            print(confidence_levels)
            print(i)

KeyError: ignored

In [157]:
print(XX_test.shape)

(26, 2700)


In [163]:
from sklearn.metrics import accuracy_score
import math
preds = []
true = []
confidences = []
for i in range(XX_test.shape[0]):
    sample_x = XX_test[i]
    sample_y = y_test[i]
    y_pred = clf.predict([sample_x])
    preds.append(y_pred)
    true.append(sample_y)
    decision_score = clf.decision_function([sample_x])[0]
    confidence_levels = math.exp(decision_score) / (1 + math.exp(decision_score))
    if y_pred == 0:
      print("goodware")
      confidences.append(confidence_levels)
      print("the confidence level is")
      print(confidence_levels)
      print(i)
    else:
      print("malware")
      print(y_pred)
      confidences.append(confidence_levels)
      print("the confidence level is")
      print(confidence_levels)
      print(i)

malware
[1]
the confidence level is
0.9999999990760093
0
malware
[1]
the confidence level is
0.9999999952996743
1
malware
[1]
the confidence level is
0.9784486798065708
2
goodware
the confidence level is
0.00776947238463927
3
malware
[1]
the confidence level is
0.9999999995540984
4
malware
[1]
the confidence level is
0.9999999995540984
5
malware
[1]
the confidence level is
0.9985702401477125
6
malware
[1]
the confidence level is
0.999999698092412
7
malware
[1]
the confidence level is
0.999999698092412
8
malware
[1]
the confidence level is
0.999999698092412
9
malware
[1]
the confidence level is
0.999999698092412
10
malware
[1]
the confidence level is
0.999999698092412
11
malware
[1]
the confidence level is
0.999999698092412
12
malware
[1]
the confidence level is
0.999999698092412
13
malware
[1]
the confidence level is
0.999999698092412
14
malware
[1]
the confidence level is
0.999999698092412
15
malware
[1]
the confidence level is
0.999999698092412
16
malware
[1]
the confidence level is


In [166]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# Assuming you have trained and fitted the classifier model, clf

# Load the validation data and labels
X_validate = validateData.values
y_validate = validateData['Malware'].values

# Feature extraction and normalization
X_validate, _ = feature_extraction(X_dataTrain, X_validate)
X_validate, _ = normalization(X_dataTrain, X_validate,errors='coerce')

# Predict using the trained model
y_pred = clf.predict(X_validate)

# Calculate evaluation metrics
accuracy = accuracy_score(y_validate, y_pred)
f1 = f1_score(y_validate, y_pred)
precision = precision_score(y_validate, y_pred)
recall = recall_score(y_validate, y_pred)

# Print the evaluation metrics
print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall:", recall)


<ipython-input-153-7c81d18fcb34>:12: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if np.issubdtype(X_dataTrain.dtype, np.object):


TypeError: ignored

In [106]:
print(XX_test.shape)

(1, 2700)


In [107]:
print(XX_train.shape)

(19620, 2700)


In [108]:
print(X_test.shape)

(1, 2700)


In [109]:

print(X_train.shape)

(19620, 2700)


In [ ]:
import pandas as pd
# Filter rows where 'EarliestModDate' is below the year 2017
filtered_df = dg[dg['EarliestModDate'].dt.year > 2017]
# Print the filtered DataFrame
print(filtered_df)
filtered_df

In [116]:
from sklearn.metrics import accuracy_score
import math
preds = []
true = []
confidences = []
# iterate over stream
print(XX_test.shape)
for i in range(XX_test.shape[0]):
    # get batch samples
    sample_x = XX_test[i]
    sample_y = y_test[i]
    # predict data
    y_pred = clf.predict([sample_x])
    # save prediction and sample_y
    preds.append(y_pred)
    true.append(sample_y)
    decision_score = clf.decision_function([sample_x])[0]
    confidence_levels = math.exp(decision_score) / (1 + math.exp(decision_score))
    if confidence_levels < 0.9:
        if y_pred == 0:
            print("goodware")
            confidences.append(confidence_levels)
            print("the confidence level is")
            print(confidence_levels)
            print(i)
        else:
            print("malware")
            print(y_pred)
            confidences.append(confidence_levels)
            print("the confidence level is")
            print(confidence_levels)
            print(i)

(1, 2700)


In [ ]:
predictions=[]
confidences=[]

from sklearn.metrics import accuracy_score
import math

preds = []
true = []
# hits

# iterate over stream
for i in range(XX_test.shape[0]):
    # get batch samples
    sample_x = XX_test[i]
    sample_y = y_test[i]
    # predict data
    y_pred = clf.predict([sample_x])

    # save prediction and sample_y
    preds.append(y_pred)
    true.append(sample_y)
    pred_prob = clf.predict_proba([sample_x])[0]
    confidence_levels=pred_prob[0]*100
    if(confidence_levels<90):
        if(y_pred==0):
            print("goodware")
            confidences.append(confidence_levels)
            print("the confidence level is")
            print(confidence_levels)
            print(i)
        else:
            print("malware")
            confidences.append(confidence_levels)
            print("the confidence level is")
            print(confidence_levels)
            print(i)








In [ ]:
import matplotlib.pyplot as plt
# interval of months to plot
months_interval = 1
# months to plot
plt_months = []
# plot years bars
last_year = years[0]
plt.axvline(-0.1,color="gray",linewidth=0.5)
plt.text(0.2,0.4,last_year, color="gray")
x_ind = 0
n_changes = 0
x_inds = []
for i, y in enumerate(years):
    if y!=last_year:
        plt.axvline(i,color="gray",linewidth=0.5)
        plt.text(i+0.3,0.4,y, color="gray")
        last_year = y
        plt_months.append("...")
        plt_months.append(months[i])
        x_ind = x_ind + 1
        n_changes = n_changes + 1
        x_inds.append(x_ind)
    else:
        plt_months.append(months[i])
        x_inds.append(x_ind)
        x_ind = x_ind + 1
plt.plot(x_inds, recall, 's-', color="green", label="Recall")
plt.plot(x_inds, precision, 'o-', color="goldenrod", label="Precision")
# plot months
plt.xticks(range(0,len(plt_months),months_interval), (plt_months))

plt.xlabel("Month")
plt.ylabel("Recall X Precision")
plt.title("REALDEVICE Incremental Windowed Classifier Update")
plt.legend(loc="center right", bbox_to_anchor=(1, 0.2))
plt.xlim(-0.33,len(plt_months)-0.66)
plt.show()

In [ ]:
accs

In [ ]:
print("Avg Accuracy:", np.mean(accs))
print("Avg F1Score:", np.mean(f1s))
print("Avg Recall:", np.mean(recall))
print("Avg Precision:", np.mean(precision))

In [ ]:
print(y_pred)

In [ ]:
from scipy.stats import mode
y_pred_2d = y_pred.reshape(-1, 1)
y_pred_mode, _ = mode(y_pred_2d, axis=1)
confidence_level = np.sum(y_pred_2d == y_pred_mode[:, np.newaxis], axis=1) / y_pred_2d.shape[1]
for row in range(len(confidence_level)):
    print("Confidence level:")
    print(confidence_level[row]*100)